// Package opensea provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package opensea

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
)

// Defines values for StatsIntervalInterval.
const (
	OneDay    StatsIntervalInterval = "one_day"
	SevenDay  StatsIntervalInterval = "seven_day"
	ThirtyDay StatsIntervalInterval = "thirty_day"
)

// Account defines model for Account.
type Account struct {
	// Address The account address
	Address string `json:"address"`

	// BannerImageUrl URL of the banner image
	BannerImageUrl string `json:"banner_image_url"`

	// Bio A short biography of the account holder
	Bio string `json:"bio"`

	// JoinedDate The date when the account was created
	JoinedDate string `json:"joined_date"`

	// ProfileImageUrl URL of the profile image
	ProfileImageUrl string `json:"profile_image_url"`

	// SocialMediaAccounts List of associated social media accounts
	SocialMediaAccounts *[]SocialMediaAccount `json:"social_media_accounts,omitempty"`

	// Username The username associated with the account
	Username string `json:"username"`

	// Website The website URL of the user
	Website string `json:"website"`
}

// Collection defines model for Collection.
type Collection struct {
	// BannerImageUrl URL of the collection's banner image
	BannerImageUrl *string `json:"banner_image_url,omitempty"`

	// Category The category of the collection
	Category *string `json:"category,omitempty"`

	// Collection The slug identifier of the collection
	Collection string `json:"collection"`

	// CollectionOffersEnabled Flags if collection offers are enabled
	CollectionOffersEnabled *bool           `json:"collection_offers_enabled,omitempty"`
	Contracts               *[]ContractInfo `json:"contracts,omitempty"`

	// CreatedDate Creation date of the collection
	CreatedDate string `json:"created_date"`

	// Description A detailed description of the collection
	Description string `json:"description"`

	// DiscordUrl Collection's Discord URL
	DiscordUrl *string `json:"discord_url,omitempty"`

	// Editors List of editor addresses
	Editors *[]string        `json:"editors,omitempty"`
	Fees    *[]CollectionFee `json:"fees,omitempty"`

	// ImageUrl URL of the collection's image
	ImageUrl string `json:"image_url"`

	// InstagramUsername Instagram username associated with the collection
	InstagramUsername *string `json:"instagram_username,omitempty"`

	// IsDisabled Whether the collection is disabled
	IsDisabled *bool `json:"is_disabled,omitempty"`

	// IsNsfw Indicates if the collection contains NSFW content
	IsNsfw *bool `json:"is_nsfw,omitempty"`

	// Name The name of the collection
	Name string `json:"name"`

	// OpenseaUrl URL to view the collection on OpenSea
	OpenseaUrl *string `json:"opensea_url,omitempty"`

	// Owner The Ethereum address of the collection owner
	Owner         string          `json:"owner"`
	PaymentTokens *[]PaymentToken `json:"payment_tokens,omitempty"`

	// ProjectUrl Official project URL
	ProjectUrl *string     `json:"project_url,omitempty"`
	Rarity     *RarityInfo `json:"rarity,omitempty"`

	// SafelistStatus The safelist status of the collection
	SafelistStatus *string `json:"safelist_status,omitempty"`

	// TelegramUrl Collection's Telegram URL
	TelegramUrl *string `json:"telegram_url,omitempty"`

	// TotalSupply Total number of items in the collection
	TotalSupply int `json:"total_supply"`

	// TraitOffersEnabled Flags if trait offers are enabled
	TraitOffersEnabled *bool `json:"trait_offers_enabled,omitempty"`

	// TwitterUsername Twitter username associated with the collection
	TwitterUsername *string `json:"twitter_username,omitempty"`

	// WikiUrl URL to the wiki page (if available)
	WikiUrl *string `json:"wiki_url,omitempty"`
}

// CollectionCriteria defines model for CollectionCriteria.
type CollectionCriteria struct {
	// Slug The slug identifier of the collection
	Slug string `json:"slug"`
}

// CollectionFee defines model for CollectionFee.
type CollectionFee struct {
	// Fee Fee percentage
	Fee *float64 `json:"fee,omitempty"`

	// Recipient Address of the fee recipient
	Recipient *string `json:"recipient,omitempty"`

	// Required Whether the fee is required
	Required *bool `json:"required,omitempty"`
}

// CollectionStats defines model for CollectionStats.
type CollectionStats struct {
	// AveragePrice Average price of items
	AveragePrice float64 `json:"average_price"`

	// FloorPrice The lowest price of items
	FloorPrice float64 `json:"floor_price"`

	// FloorPriceSymbol The currency symbol for floor price
	FloorPriceSymbol string `json:"floor_price_symbol"`

	// MarketCap The market cap
	MarketCap float64 `json:"market_cap"`

	// NumOwners Number of unique owners
	NumOwners int `json:"num_owners"`

	// Sales Total sales transactions
	Sales float64 `json:"sales"`

	// Volume Total trading volume
	Volume float64 `json:"volume"`
}

// CollectionStatsResponse defines model for CollectionStatsResponse.
type CollectionStatsResponse struct {
	Intervals []StatsInterval `json:"intervals"`
	Total     CollectionStats `json:"total"`
}

// ConsiderationItem defines model for ConsiderationItem.
type ConsiderationItem struct {
	// EndAmount The ending amount in wei as a string
	EndAmount string `json:"endAmount"`

	// IdentifierOrCriteria Identifier or criteria for the token
	IdentifierOrCriteria int64 `json:"identifierOrCriteria"`

	// ItemType The type of item (e.g., 1 for ERC20)
	ItemType int `json:"itemType"`

	// Recipient Address of the recipient
	Recipient string `json:"recipient"`

	// StartAmount The starting amount in wei as a string
	StartAmount string `json:"startAmount"`

	// Token Token address
	Token string `json:"token"`
}

// ContractCriteria defines model for ContractCriteria.
type ContractCriteria struct {
	// Address The contract address
	Address string `json:"address"`
}

// ContractInfo defines model for ContractInfo.
type ContractInfo struct {
	// Address Contract address
	Address *string `json:"address,omitempty"`

	// Chain Blockchain of the contract
	Chain *string `json:"chain,omitempty"`
}

// CriteriaOffer defines model for CriteriaOffer.
type CriteriaOffer struct {
	Criteria OfferCriteria `json:"criteria"`

	// ProtocolAddress The exchange contract address
	ProtocolAddress string       `json:"protocol_address"`
	ProtocolData    ProtocolData `json:"protocol_data"`
}

// CriteriaOfferResponse defines model for CriteriaOfferResponse.
type CriteriaOfferResponse struct {
	Chain     string `json:"chain"`
	OrderHash string `json:"order_hash"`
	Price     *Price `json:"price,omitempty"`
}

// Offer defines model for Offer.
type Offer struct {
	// Chain The blockchain on which the offer exists
	Chain    string `json:"chain"`
	Criteria *struct {
		Collection CollectionCriteria `json:"collection"`
		Contract   ContractCriteria   `json:"contract"`

		// EncodedTokenIds Encoded token IDs. Use "*" for all tokens
		EncodedTokenIds *string        `json:"encoded_token_ids,omitempty"`
		Trait           *TraitCriteria `json:"trait,omitempty"`
	} `json:"criteria,omitempty"`

	// OrderHash The hash of the order
	OrderHash string `json:"order_hash"`
	Price     Price  `json:"price"`

	// ProtocolAddress The protocol address
	ProtocolAddress *string       `json:"protocol_address,omitempty"`
	ProtocolData    *ProtocolData `json:"protocol_data,omitempty"`
}

// OfferCriteria defines model for OfferCriteria.
type OfferCriteria struct {
	Collection CollectionCriteria `json:"collection"`
	Contract   ContractCriteria   `json:"contract"`

	// EncodedTokenIds List of token IDs matching criteria
	EncodedTokenIds *string `json:"encoded_token_ids,omitempty"`
}

// OfferItem defines model for OfferItem.
type OfferItem struct {
	// EndAmount The ending amount in wei as a string
	EndAmount string `json:"endAmount"`

	// IdentifierOrCriteria Identifier or criteria for the token
	IdentifierOrCriteria int64 `json:"identifierOrCriteria"`

	// ItemType The type of item (e.g., 1 for ERC20)
	ItemType int `json:"itemType"`

	// StartAmount The starting amount in wei as a string
	StartAmount string `json:"startAmount"`

	// Token Token address
	Token string `json:"token"`
}

// OffersResponse defines model for OffersResponse.
type OffersResponse struct {
	Offers []Offer `json:"offers"`
}

// PaymentToken defines model for PaymentToken.
type PaymentToken struct {
	// Address Address of the payment token
	Address *string `json:"address,omitempty"`

	// Chain Blockchain of the payment token
	Chain *string `json:"chain,omitempty"`

	// Decimals Number of decimals of the token
	Decimals *int `json:"decimals,omitempty"`

	// EthPrice Price of the token in ETH
	EthPrice *string `json:"eth_price,omitempty"`

	// Image URL of the payment token's image
	Image *string `json:"image,omitempty"`

	// Name Name of the token
	Name *string `json:"name,omitempty"`

	// Symbol Payment token symbol
	Symbol *string `json:"symbol,omitempty"`

	// UsdPrice Price of the token in USD
	UsdPrice *string `json:"usd_price,omitempty"`
}

// Price defines model for Price.
type Price struct {
	// Currency The currency used (e.g., "WETH")
	Currency string `json:"currency"`

	// Decimals Number of decimals for the currency
	Decimals int `json:"decimals"`

	// Value The value in currency units
	Value string `json:"value"`
}

// ProtocolData defines model for ProtocolData.
type ProtocolData struct {
	Parameters ProtocolParameters `json:"parameters"`

	// Signature The signature of the protocol data
	Signature *string `json:"signature,omitempty"`
}

// ProtocolParameters defines model for ProtocolParameters.
type ProtocolParameters struct {
	// ConduitKey The conduit key for the order
	ConduitKey    string              `json:"conduitKey"`
	Consideration []ConsiderationItem `json:"consideration"`

	// Counter Must match the current counter for the given offerer. If you are unsure of the current counter, it can be read from the contract on etherscan.
	Counter string `json:"counter"`

	// EndTime The end time as a Unix timestamp in seconds
	EndTime string      `json:"endTime"`
	Offer   []OfferItem `json:"offer"`

	// Offerer Address of the offerer
	Offerer string `json:"offerer"`

	// OrderType The type of order
	OrderType int `json:"orderType"`

	// Salt A unique value to prevent duplicate orders
	Salt string `json:"salt"`

	// StartTime The start time as a Unix timestamp in seconds
	StartTime string `json:"startTime"`

	// TotalOriginalConsiderationItems Total number of original consideration items
	TotalOriginalConsiderationItems int `json:"totalOriginalConsiderationItems"`

	// Zone Address of the zone
	Zone string `json:"zone"`

	// ZoneHash The hash of the zone
	ZoneHash string `json:"zoneHash"`
}

// RarityInfo defines model for RarityInfo.
type RarityInfo struct {
	// CalculatedAt Timestamp when the rarity was calculated
	CalculatedAt *string `json:"calculated_at,omitempty"`

	// MaxRank Maximum rank of tokens
	MaxRank *int `json:"max_rank,omitempty"`

	// StrategyId Rarity calculation strategy identifier
	StrategyId *string `json:"strategy_id,omitempty"`

	// StrategyVersion Version of the rarity calculation strategy
	StrategyVersion *string `json:"strategy_version,omitempty"`

	// TokensScored Number of tokens scored
	TokensScored *int `json:"tokens_scored,omitempty"`
}

// SocialMediaAccount defines model for SocialMediaAccount.
type SocialMediaAccount struct {
	// Platform Social media platform name
	Platform *string `json:"platform,omitempty"`

	// Username Social media username
	Username *string `json:"username,omitempty"`
}

// StatsInterval defines model for StatsInterval.
type StatsInterval struct {
	// AveragePrice Average price during interval
	AveragePrice float64 `json:"average_price"`

	// Interval The interval period
	Interval StatsIntervalInterval `json:"interval"`

	// Sales Number of sales
	Sales float64 `json:"sales"`

	// SalesDiff Sales difference vs previous interval
	SalesDiff float64 `json:"sales_diff"`

	// Volume Trading volume during interval
	Volume float64 `json:"volume"`

	// VolumeChange Percentage volume change
	VolumeChange float64 `json:"volume_change"`

	// VolumeDiff Volume difference vs previous interval
	VolumeDiff float64 `json:"volume_diff"`
}

// StatsIntervalInterval The interval period
type StatsIntervalInterval string

// TraitCriteria defines model for TraitCriteria.
type TraitCriteria struct {
	// Type The type of the trait (e.g., "Background")
	Type string `json:"type"`

	// Value The value of the trait (e.g., "Yellow")
	Value string `json:"value"`
}

// CancelOrderJSONBody defines parameters for CancelOrder.
type CancelOrderJSONBody struct {
	// OffererSignature An EIP-712 signature from the offerer of the order. If this is not provided, the user associated with the API Key will be checked instead. The signature must be a EIP-712 signature consisting of the order's Seaport contract's name, version, address, and chain. The struct to sign is OrderHash containing a single bytes32 field.
	OffererSignature *string `json:"offererSignature,omitempty"`
}

// CreateCriteriaOfferJSONRequestBody defines body for CreateCriteriaOffer for application/json ContentType.
type CreateCriteriaOfferJSONRequestBody = CriteriaOffer

// CancelOrderJSONRequestBody defines body for CancelOrder for application/json ContentType.
type CancelOrderJSONRequestBody CancelOrderJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAccount request
	GetAccount(ctx context.Context, username string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCollection request
	GetCollection(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCollectionStats request
	GetCollectionStats(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCriteriaOfferWithBody request with any body
	CreateCriteriaOfferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCriteriaOffer(ctx context.Context, body CreateCriteriaOfferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCollectionOffers request
	GetCollectionOffers(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelOrderWithBody request with any body
	CancelOrderWithBody(ctx context.Context, chain string, protocolAddress string, orderHash string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CancelOrder(ctx context.Context, chain string, protocolAddress string, orderHash string, body CancelOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAccount(ctx context.Context, username string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAccountRequest(c.Server, username)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCollection(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCollectionRequest(c.Server, collectionSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCollectionStats(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCollectionStatsRequest(c.Server, collectionSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCriteriaOfferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCriteriaOfferRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCriteriaOffer(ctx context.Context, body CreateCriteriaOfferJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCriteriaOfferRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCollectionOffers(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCollectionOffersRequest(c.Server, collectionSlug)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelOrderWithBody(ctx context.Context, chain string, protocolAddress string, orderHash string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelOrderRequestWithBody(c.Server, chain, protocolAddress, orderHash, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelOrder(ctx context.Context, chain string, protocolAddress string, orderHash string, body CancelOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelOrderRequest(c.Server, chain, protocolAddress, orderHash, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAccountRequest generates requests for GetAccount
func NewGetAccountRequest(server string, username string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "username", runtime.ParamLocationPath, username)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCollectionRequest generates requests for GetCollection
func NewGetCollectionRequest(server string, collectionSlug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "collection_slug", runtime.ParamLocationPath, collectionSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/collections/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCollectionStatsRequest generates requests for GetCollectionStats
func NewGetCollectionStatsRequest(server string, collectionSlug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "collection_slug", runtime.ParamLocationPath, collectionSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/collections/%s/stats", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCriteriaOfferRequest calls the generic CreateCriteriaOffer builder with application/json body
func NewCreateCriteriaOfferRequest(server string, body CreateCriteriaOfferJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCriteriaOfferRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCriteriaOfferRequestWithBody generates requests for CreateCriteriaOffer with any type of body
func NewCreateCriteriaOfferRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/offers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCollectionOffersRequest generates requests for GetCollectionOffers
func NewGetCollectionOffersRequest(server string, collectionSlug string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "collection_slug", runtime.ParamLocationPath, collectionSlug)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/offers/collection/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelOrderRequest calls the generic CancelOrder builder with application/json body
func NewCancelOrderRequest(server string, chain string, protocolAddress string, orderHash string, body CancelOrderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCancelOrderRequestWithBody(server, chain, protocolAddress, orderHash, "application/json", bodyReader)
}

// NewCancelOrderRequestWithBody generates requests for CancelOrder with any type of body
func NewCancelOrderRequestWithBody(server string, chain string, protocolAddress string, orderHash string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "chain", runtime.ParamLocationPath, chain)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "protocol_address", runtime.ParamLocationPath, protocolAddress)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "order_hash", runtime.ParamLocationPath, orderHash)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/orders/chain/%s/protocol/%s/%s/cancel", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAccountWithResponse request
	GetAccountWithResponse(ctx context.Context, username string, reqEditors ...RequestEditorFn) (*GetAccountResponse, error)

	// GetCollectionWithResponse request
	GetCollectionWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionResponse, error)

	// GetCollectionStatsWithResponse request
	GetCollectionStatsWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionStatsResponse, error)

	// CreateCriteriaOfferWithBodyWithResponse request with any body
	CreateCriteriaOfferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCriteriaOfferResponse, error)

	CreateCriteriaOfferWithResponse(ctx context.Context, body CreateCriteriaOfferJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCriteriaOfferResponse, error)

	// GetCollectionOffersWithResponse request
	GetCollectionOffersWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionOffersResponse, error)

	// CancelOrderWithBodyWithResponse request with any body
	CancelOrderWithBodyWithResponse(ctx context.Context, chain string, protocolAddress string, orderHash string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelOrderResponse, error)

	CancelOrderWithResponse(ctx context.Context, chain string, protocolAddress string, orderHash string, body CancelOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelOrderResponse, error)
}

type GetAccountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Account
}

// Status returns HTTPResponse.Status
func (r GetAccountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAccountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCollectionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Collection
}

// Status returns HTTPResponse.Status
func (r GetCollectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCollectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCollectionStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CollectionStatsResponse
}

// Status returns HTTPResponse.Status
func (r GetCollectionStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCollectionStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCriteriaOfferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CriteriaOfferResponse
}

// Status returns HTTPResponse.Status
func (r CreateCriteriaOfferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCriteriaOfferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCollectionOffersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OffersResponse
}

// Status returns HTTPResponse.Status
func (r GetCollectionOffersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCollectionOffersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		LastSignatureIssuedValidUntil *string `json:"last_signature_issued_valid_until,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CancelOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAccountWithResponse request returning *GetAccountResponse
func (c *ClientWithResponses) GetAccountWithResponse(ctx context.Context, username string, reqEditors ...RequestEditorFn) (*GetAccountResponse, error) {
	rsp, err := c.GetAccount(ctx, username, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAccountResponse(rsp)
}

// GetCollectionWithResponse request returning *GetCollectionResponse
func (c *ClientWithResponses) GetCollectionWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionResponse, error) {
	rsp, err := c.GetCollection(ctx, collectionSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCollectionResponse(rsp)
}

// GetCollectionStatsWithResponse request returning *GetCollectionStatsResponse
func (c *ClientWithResponses) GetCollectionStatsWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionStatsResponse, error) {
	rsp, err := c.GetCollectionStats(ctx, collectionSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCollectionStatsResponse(rsp)
}

// CreateCriteriaOfferWithBodyWithResponse request with arbitrary body returning *CreateCriteriaOfferResponse
func (c *ClientWithResponses) CreateCriteriaOfferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCriteriaOfferResponse, error) {
	rsp, err := c.CreateCriteriaOfferWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCriteriaOfferResponse(rsp)
}

func (c *ClientWithResponses) CreateCriteriaOfferWithResponse(ctx context.Context, body CreateCriteriaOfferJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCriteriaOfferResponse, error) {
	rsp, err := c.CreateCriteriaOffer(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCriteriaOfferResponse(rsp)
}

// GetCollectionOffersWithResponse request returning *GetCollectionOffersResponse
func (c *ClientWithResponses) GetCollectionOffersWithResponse(ctx context.Context, collectionSlug string, reqEditors ...RequestEditorFn) (*GetCollectionOffersResponse, error) {
	rsp, err := c.GetCollectionOffers(ctx, collectionSlug, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCollectionOffersResponse(rsp)
}

// CancelOrderWithBodyWithResponse request with arbitrary body returning *CancelOrderResponse
func (c *ClientWithResponses) CancelOrderWithBodyWithResponse(ctx context.Context, chain string, protocolAddress string, orderHash string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelOrderResponse, error) {
	rsp, err := c.CancelOrderWithBody(ctx, chain, protocolAddress, orderHash, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelOrderResponse(rsp)
}

func (c *ClientWithResponses) CancelOrderWithResponse(ctx context.Context, chain string, protocolAddress string, orderHash string, body CancelOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelOrderResponse, error) {
	rsp, err := c.CancelOrder(ctx, chain, protocolAddress, orderHash, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelOrderResponse(rsp)
}

// ParseGetAccountResponse parses an HTTP response from a GetAccountWithResponse call
func ParseGetAccountResponse(rsp *http.Response) (*GetAccountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAccountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Account
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetCollectionResponse parses an HTTP response from a GetCollectionWithResponse call
func ParseGetCollectionResponse(rsp *http.Response) (*GetCollectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCollectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Collection
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetCollectionStatsResponse parses an HTTP response from a GetCollectionStatsWithResponse call
func ParseGetCollectionStatsResponse(rsp *http.Response) (*GetCollectionStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCollectionStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CollectionStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateCriteriaOfferResponse parses an HTTP response from a CreateCriteriaOfferWithResponse call
func ParseCreateCriteriaOfferResponse(rsp *http.Response) (*CreateCriteriaOfferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCriteriaOfferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CriteriaOfferResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetCollectionOffersResponse parses an HTTP response from a GetCollectionOffersWithResponse call
func ParseGetCollectionOffersResponse(rsp *http.Response) (*GetCollectionOffersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCollectionOffersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OffersResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCancelOrderResponse parses an HTTP response from a CancelOrderWithResponse call
func ParseCancelOrderResponse(rsp *http.Response) (*CancelOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			LastSignatureIssuedValidUntil *string `json:"last_signature_issued_valid_until,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
